### ISSUE TITLE
There is no 'register a new user' link on the main page, thus docs are broken

### ISSUE THREAD

**Issue by amateusz** [OpenframeProject/openframeproject.github.io#2]
[First step in docs](http://docs.openframe.io/frame-setup-guide/#1-create-a-user-account) points to the [main page](openframe.io) but there - in turn - is no `new user`/`register`/`sign up` button.

The only way - I could find - to actually register a new account is to select some artwork, `push it to frame` and then `create an account`

**Comment by amateusz** [comment]
hm, maybe make it point to ["web app"](https://openframe.io/stream) ? This division is strange for me, but will now I kind of see the difference between this two pages.

**Comment by jvolker** [comment]
You're right. A direct route/URL to the account creation form is yet to be created in the web app. There is a new issue in the Web-App repo: https://github.com/OpenframeProject/Openframe-WebApp/issues/13 

I've updated the docs though. They are now pointing to the login form of the web app where you get a "Create an account" link. 

Could you please close this issue here?  I don't have permission to do this.
